#!/usr/bin/env php
<?php

function run_tests(): int
{
    $status = 0;
    passthru(
        sprintf(
            "%s/vendor/bin/phpunit --configuration=%s/tests/phpunit.xml %s/tests",
            __DIR__,
            __DIR__,
            __DIR__
        ),
        $status,
    );
    return $status;
}

function run_static_analysis(): int
{
    $status = 0;
    passthru(
        sprintf(
            "%s/vendor/bin/phpstan",
            __DIR__
        ),
        $status
    );
    return $status;
}

$test_status = run_tests();
$analysis_status = run_static_analysis();
printf("PHPUnit Tests: ..................... %s\n", $test_status === 0 ? "👍" : "👎");
printf("PHPStan Static Analysis: ........... %s\n", $test_status === 0 ? "👍" : "👎");
exit($test_status + $analysis_status);
